v1.3.0
eastgenomics/eggd_generate_bed pull request #27
Opened 2024-01-11 11:16 UTC by growland2

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27)

2024-01-11 11:16 UTC, pep8speaks commented
Hello @growland2! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`resources/home/dnanexus/generate_bed.py`](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py):

> [Line 61:1](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L61): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 63:2](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L63): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 65:73](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L65): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 72:80](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L72): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 79:14](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L79): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 80:14](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L80): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 81:5](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L81): [E124](https://duckduckgo.com/?q=pep8%20E124) closing bracket does not match visual indentation
> [Line 92:1](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L92): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 94:76](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L94): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 99:1](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L99): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 117:80](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L117): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 121:1](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L121): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 126:40](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L126): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 135:80](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L135): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 135:81](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L135): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 141:45](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L141): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 160:1](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L160): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 163:1](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L163): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 171:80](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L171): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 177:5](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L177): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 179:1](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L179): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 180:5](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L180): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line
> [Line 190:70](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L190): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 194:54](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L194): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 215:1](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L215): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 216:5](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L216): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line
> [Line 216:5](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L216): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 225:69](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L225): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 293:13](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L293): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 293:26](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L293): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 299:9](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L299): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 306:80](https://github.com/eastgenomics/eggd_generate_bed/blob/dc96328f3d4f485491490140a2603a59f8eff99e/resources/home/dnanexus/generate_bed.py#L306): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)

* In the [...]

2024-01-12 12:45 UTC, jethror1 requested changes
> Reviewed 5 of 10 files at r1, 3 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27)* status: 8 of 10 files reviewed, 18 unresolved discussions (waiting on @growland2)

___
*[`resources/home/dnanexus/generate_bed.py` line 75 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-Nnx6Hl88dBaoT8Y1ydg:-Nnx6Hl88dBaoT8Y1ydh:b-dcdv6m) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/ddc4f020aa32822a50596ec2fb9be08309e115f4/resources/home/dnanexus/generate_bed.py#L75)):*
> ```Python
>         col_names (list): list of column names to be used as headers (optional)
>         case_change (dict): dictionary specifying the column and desired case
>         to which the column will be changed to upper or lower (optional)
> ```

really tiny thing but when you have continuation lines in a docstring it can make readability easier if its indented to make it distinct from new inputs, especially when you have a lot of inputs



_Code quote:_
```Python
to which the column will be changed to upper or lower (optional)
```
___
*[`resources/home/dnanexus/generate_bed.py` line 88 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxDnP12mkgVWYx1yPL:-NnxDnP12mkgVWYx1yPM:b-kbx7jw) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/ddc4f020aa32822a50596ec2fb9be08309e115f4/resources/home/dnanexus/generate_bed.py#L88)):*
> ```Python
>     df = pd.read_csv(file_name, sep=sep, names=col_names, dtype=dtypes)
> 
>     if case_change is not None:
> ```

unless you explicitly need to check for `None` vs `False` or zero etc, it's more Pythonic to just do `if case_change:`



_Code quote:_
```Python
if case_change is not None:
```
___
*[`resources/home/dnanexus/generate_bed.py` line 97 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxEBEK-sRlIQ2oCRPr:-NnxEBEK-sRlIQ2oCRPs:b-33ws4w) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/ddc4f020aa32822a50596ec2fb9be08309e115f4/resources/home/dnanexus/generate_bed.py#L97)):*
> ```Python
> 
> 
> def get_g_build(exons_file: str) -> str:
> ```

I'd go with calling it `get_genome_build` to be more explicit



_Code quote:_
```Python
get_g_build
```
___
*[`resources/home/dnanexus/generate_bed.py` line 138 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxFFzM7rrzBtL3kVpY:-NnxFFzM7rrzBtL3kVpZ:bcfuvom) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/ddc4f020aa32822a50596ec2fb9be08309e115f4/resources/home/dnanexus/generate_bed.py#L138)):*
> ```Python
>         g2t (df): df of genes2transcripts file
>         gene_panels (df): df of gene_panels file
> ```

would be nice to add to the docstring a `Raises` section like you did previously for the assertion errors
___
*[`resources/home/dnanexus/generate_bed.py` line 143 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxEifd87ypeaf0UaKU:-NnxEifd87ypeaf0UaKV:b982pc8) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/ddc4f020aa32822a50596ec2fb9be08309e115f4/resources/home/dnanexus/generate_bed.py#L143)):*
> ```Python
>         genes (list): list of unique genes across all specified panels/genes
>     """
>     panels = list(filter(None, [x.strip() for x in panel_list.split(";")]))
> ```

reminder to me to think about this as it might change



_Code quote:_
```Python
panel_list.split(";")]))
```
___
*[`resources/home/dnanexus/generate_bed.py` line 176 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxFnc87TyCMCYTH-Sa:-NnxFnc87TyCMCYTH-Sb:bjy6rrv) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/ddc4f020aa32822a50596ec2fb9be08309e115f4/resources/home/dnanexus/generate_bed.py#L176)):*
> ```Python
>     Returns:
>         additional_regions (df): df of additional_regions file
>     """
> ```

Missing `Raises` from docstring
___
*[`resources/home/dnanexus/generate_bed.py` line 200 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxG4yRCx9Hk1GZWzNX:-NnxG4yRCx9Hk1GZWzNY:b-7hpvb9) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/5ce5476c068232643a5d264b08399b67d776a620/resources/home/dnanexus/generate_bed.py#L200)):*
> ```Python
>     Returns:
>         list: list of clinical transcripts corresponding to each gene
>     """
> ```

missing `Raises` from docstring
___
*[`resources/home/dnanexus/generate_bed.py` line 254 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxGEmW8a_wiP49SUQc:-NnxGEmW8a_wiP49SUQd:b-ymzoob) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/5ce5476c068232643a5d264b08399b67d776a620/resources/home/dnanexus/generate_bed.py#L254)):*
> ```Python
>     ]
> 
>     if additional_regions is not None:
> ```

`if additional_regions:`



_Code quote:_
```Python
if additional_regions is not None:
```
___
*[`resources/home/dnanexus/generate_bed.py` line 262 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxGKgd7NMAH-lHo_In:-NnxGKgd7NMAH-lHo_Io:b-q3x8ne) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/5ce5476c068232643a5d264b08399b67d776a620/resources/home/dnanexus/generate_bed.py#L262)):*
> ```Python
> 
>     # apply flank to start and end if given
>     if flank is not None:
> ```

`if flank:`



_Code quote:_
```Python
if flank is not None:
```
___
*[`resources/home/dnanexus/generate_bed.py` line 289 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxGU0a6790Ul0-WRy6:-NnxGU0a6790Ul0-WRy7:b-q3x8ne) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/5ce5476c068232643a5d264b08399b67d776a620/resources/home/dnanexus/generate_bed.py#L289)):*
> ```Python
>             output_prefix = "&&".join(panels)
> 
>     if flank is not None:
> ```

`if flank:`



_Code quote:_
```Python
if flank is not None:
```
___
*[`resources/home/dnanexus/generate_bed.py` line 319 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxGiUI5Y8UXrtZsTJS:-NnxGiUJBoptgE7Oz4GM:bg08rp2) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/5ce5476c068232643a5d264b08399b67d776a620/resources/home/dnanexus/generate_bed.py#L319)):*
> ```Python
>     transcripts = get_transcripts(g2t, genes, exons)
> 
>     if args.additional_regions is not None:
> ```

`if args.additional_regions:`



_Code quote:_
```Python
if args.additional_regions is not None:
```
___
*[`resources/home/dnanexus/tests/test_generate_bed.py` line 85 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxHG7TBG5Mq-f50Qqa:-NnxHG7UE6yWN3K67nd9:b-bhc7xg) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/5ce5476c068232643a5d264b08399b67d776a620/resources/home/dnanexus/tests/test_generate_bed.py#L85)):*
> ```Python
> 
> class TestGetGBuild:
>     """Methods to test get_g_build() function from generate_bed.py"""
> ```

if you change the function name this should change too



_Code quote:_
```Python
get_g_build()
```
___
*[`resources/home/dnanexus/tests/test_generate_bed.py` line 127 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxHWl9441RaxfNrgrt:-NnxHWl9441RaxfNrgru:b-5crbld) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/5ce5476c068232643a5d264b08399b67d776a620/resources/home/dnanexus/tests/test_generate_bed.py#L127)):*
> ```Python
>         ambig_file = "GCF_000001405.25_GRCh37_GRCh38.p13_genomic.exon_5bp.tsv"
>         with pytest.raises(ValueError):
>             gb.get_g_build(ambig_file)
> ```

when testing for multiple of the same Exception being raised from one function, you can check the correct error is being raised by using the `match` parameter for `pytest.raises()`, something like:

```
expected = f'Ambiguous genome build in exon's file {ambig_file}'

with pytest.raises(ValueError, match=expected):
    gb.get_g_build(ambig_file)
```

this ensures your test is ac [...]

2024-01-16 09:15 UTC, growland2 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27)* status: 8 of 10 files reviewed, 18 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/generate_bed.py` line 75 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-Nnx6Hl88dBaoT8Y1ydg:-NoGWnyq5K_-7vRQsr_5:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/ddc4f020aa32822a50596ec2fb9be08309e115f4/resources/home/dnanexus/generate_bed.py#L75)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

really tiny thing but when you have continuation lines in a docstring it can make readability easier if its indented to make it distinct from new inputs, especially when you have a lot of inputs
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_bed.py` line 88 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxDnP12mkgVWYx1yPL:-NoGWot6BGbbFW2Fyulm:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/ddc4f020aa32822a50596ec2fb9be08309e115f4/resources/home/dnanexus/generate_bed.py#L88)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

unless you explicitly need to check for `None` vs `False` or zero etc, it's more Pythonic to just do `if case_change:`
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_bed.py` line 97 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxEBEK-sRlIQ2oCRPr:-NoGWpS23YEyfEFC6urv:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/ddc4f020aa32822a50596ec2fb9be08309e115f4/resources/home/dnanexus/generate_bed.py#L97)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I'd go with calling it `get_genome_build` to be more explicit
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_bed.py` line 138 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxFFzM7rrzBtL3kVpY:-NoGWqJrCetmIIjEjIFP:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/ddc4f020aa32822a50596ec2fb9be08309e115f4/resources/home/dnanexus/generate_bed.py#L138)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

would be nice to add to the docstring a `Raises` section like you did previously for the assertion errors
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_bed.py` line 176 at r2](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxFnc87TyCMCYTH-Sa:-NoGX-3nEYaIo0wi3Dqa:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/ddc4f020aa32822a50596ec2fb9be08309e115f4/resources/home/dnanexus/generate_bed.py#L176)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

Missing `Raises` from docstring
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_bed.py` line 200 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxG4yRCx9Hk1GZWzNX:-NoGX5536aQXyTItKiCS:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/5ce5476c068232643a5d264b08399b67d776a620/resources/home/dnanexus/generate_bed.py#L200)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

missing `Raises` from docstring
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_bed.py` line 254 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxGEmW8a_wiP49SUQc:-NoGX8mjBwGxi-eM2Muf:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/5ce5476c068232643a5d264b08399b67d776a620/resources/home/dnanexus/generate_bed.py#L254)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

`if additional_regions:`
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_bed.py` line 262 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxGKgd7NMAH-lHo_In:-NoGX9vP6HNGUfY4gjDw:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/5ce5476c068232643a5d264b08399b67d776a620/resources/home/dnanexus/generate_bed.py#L262)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

`if flank:`
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_bed.py` line 289 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxGU0a6790Ul0-WRy6:-NoGXBkAE2bYGNT5ASSa:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/5ce5476c068232643a5d264b08399b67d776a620/resources/home/dnanexus/generate_bed.py#L289)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

`if flank:`
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_bed.py` line 319 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxGiUI5Y8UXrtZsTJS:-NoGXEXgDgE0_ER_suFF:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/5ce5476c068232643a5d264b08399b67d776a620/resources/home/dnanexus/generate_bed.py#L319)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

`if args.additional_regions:`
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/tests/test_generate_bed.py` line 85 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxHG7TBG5Mq-f50Qqa:-NoGXakwDyxL22IGwMh-:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/5ce5476c068232643a5d264b08399b67d776a620/resources/home/dnanexus/tests/test_generate_bed.py#L85)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

if you change the function name this should change too
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/tests/test_generate_bed.py` line 127 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxHWl9441RaxfNrgrt:-NoGXjOw8-tF4QL9k3iU:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/5ce5476c068232643a5d264b08399b67d776a620/resources/home/dnanexus/tests/test_generate_bed.py#L127)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

when testing for multiple of the same Exception being raised from one function, you can check the correct error is being raised by using the `match` parameter for `pytest.raises()`, something like:

```
expected = f'Ambiguous genome build in exon's file {ambig_file}'

with pytest.raises(ValueError, match=expected):
    gb.get_g_build(ambig_file)
```

this ensures your test is actually catching the correct error
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/tests/test_generate_bed.py` line 130 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxI7RQEmlqUMzGw7Dl:-NoGXnG5CfB8P7nogR7l:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/5ce5476c068232643a5d264b08399b67d776a620/resources/home/dnanexus/tests/test_generate_bed.py#L130)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

test class and docstring don't match your function name (I assume this is for `read_genes_and_panels()`)
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/tests/test_generate_bed.py` line 133 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27#-NnxIQA_4m57VTvpLaNN:-NoGY-UfADDXka25xNry:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_bed/blob/5ce5476c068232643a5d264b08399b67d776a620/resources/home/dnanexus/tests/test_generate_bed.py#L133)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

would be good to add to here a test that when you specify valid inputs, that the function returns what you expect as we [...]

2024-01-16 10:01 UTC, jethror1 approved these changes
> Reviewed 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_bed/27)* status: 10 of 11 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-01-16 10:02 UTC, merged